"use strict";
exports.__esModule = true;
var Exercise6_1 = require("./Exercise/Exercise6");
// Exercise1.question1();
// Exercise1.question2();
// Exercise2.question1();
// Exercise2.question2();
// Exercise2.question3();
// Exercise3.question1();
// Exercise3.question2();
// Exercise3.question3();
// Exercise4.question1();
// Exercise4.question2();
// Exercise5.question1();
// Exercise5.question2();
// Exercise5.question3();
// Exercise5_CallBack.question1();
// Exercise6.question1;
Exercise6_1["default"].question2;
